version: '3'

services:
  transactioneer:
    restart: always
    ports:
      - "7991:7991"
    build:
      dockerfile: ./spot/transactioneer.Dockerfile
    environment:
      - main_address=0x2DBc451a2BAd2aDFfEF5d69C393A423D02D4f531
    init: true
    working_dir: /app/
    command: python3.10 /app/transactioneer.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7991/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s
  batch_processor:
    restart: always
    ports:
      - "7999:7999"
    build:
      dockerfile: ./spot/Dockerfile
    environment:
      - main_address=0x2DBc451a2BAd2aDFfEF5d69C393A423D02D4f531 # todo: remove
      - transactioneer=http://transactioneer:7991
    init: true
    working_dir: /app/
    command: python3.10 /app/batch_processor.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7999/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 6G
  processor:
    restart: always
    ports:
      - "7998:7998"
    build:
      dockerfile: ./spot/Dockerfile
    environment:
      - main_address=0x2DBc451a2BAd2aDFfEF5d69C393A423D02D4f531 # todo remove
      - batch_target=http://batch_processor:7999
    init: true
    working_dir: /app/
    command: python3.10 /app/item_processor.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7998/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 6G
  scraper:
    restart: always
    ports:
      - "8000:8000"
    build:
      dockerfile: ./scrap/Dockerfile
    init: true
    working_dir: /app/
    command: python3.10 /app/scraper.py
    environment:
      - PORT=8000
      - youtube00e1f862e5eff=1
      - ap98j3envoubi3fco1kc=1
      - ch4875eda56be56000ac=1
      - masto65ezfd86424f69a=1
      - rss007d0675444aa13fc=1
      - wei223be19ab11e891bo=1
      - hackbc9419ab11eebe56=1
      - tradview251ae30a11ee=1
      - bitcointalk4de40ec26=1
      - jvc8439846094ced03ff=1
      - a7df32de3a60dfdb7a0b=1
      - spotting_target=http://processor:7998
    depends_on:
      - batch_processor
      - processor
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G