version: '3'

services:
  spotting:
    ports:
      - "7999:7999"
    build:
      dockerfile: ./spot/Dockerfile
    environment:
      - main_address=0x2DBc451a2BAd2aDFfEF5d69C393A423D02D4f53m
    init: true
    working_dir: /app/
    command: python3.10 /app/spotting.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7999/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s
  scraper:
    ports:
      - "8000:8000"
    build:
      dockerfile: ./scrap/Dockerfile
    init: true
    working_dir: /app/
    command: python3.10 /app/scraper.py
    environment:
      - PORT=8000
      - youtube00e1f862e5eff=1
      - ap98j3envoubi3fco1kc=1
      - ch4875eda56be56000ac=1
      - masto65ezfd86424f69a=1
      - rss007d0675444aa13fc=1
      - wei223be19ab11e891bo=1
      - hackbc9419ab11eebe56=1
      - tradview251ae30a11ee=1
      - bitcointalk4de40ec26=1
      - jvc8439846094ced03ff=1
      - a7df32de3a60dfdb7a0b=1
      - spotting_target=http://spotting:7999
    depends_on:
      spotting:
        condition: service_healthy
