version: '3.9'

services:
  upipe:
    image: exordelabs/upipe:latest
    networks:
      - exorde-network
    ports:
      - "7997-7998:8000"
    labels:
      - "network.exorde.monitor=true"
      - "network.exorde.service=upipe"
    restart: always
    environment:
      - TRACE=true
      - TIMEOUT=5
    init: true
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 6G
          devices:
           - driver: nvidia
             device_ids: ['0']
             capabilities: [gpu]

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s



  bpipe:
    image: exordelabs/bpipe:latest
    networks:
      - exorde-network
    ports:
      - "7999:8000"
    labels:
      - "network.exorde.monitor=true"
      - "network.exorde.service=bpipe"
    restart: always
    environment:
      - batch_size=20
      - TRACE=true
    init: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 6G
          devices:
           - driver: nvidia
             device_ids: ['0']
             capabilities: [gpu]

  transactioneer:
    image: exordelabs/transactioneer:latest
    networks:
      - exorde-network
    labels:
      - "network.exorde.monitor=true"
      - "network.exorde.service=transactioneer"
    volumes:
      - ./config:/root/.config
    restart: always
    ports:
      - "7991:8000"
    environment:
      - main_address=0x60e0f0f100B22e1783B4B4DB68a1115aEaCD0f3C
      - TRACE=true
    init: true
    working_dir: /app/
    command: python3.10 /app/transactioneer.py
    deploy:
      replicas: ${TRANSACTIONEER_SIZE:-1}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s

  orchestrator:
    image: exordelabs/orchestrator:alpha
    labels:
      - "network.exorde.monitor=true"
      - "network.exorde.service=orchestrator"
    networks:
      - exorde-network
    restart: always
    environment:
      - PROMETHEUS_TARGET_DISCOVERY_LABEL=network.exorde.monitor:true
      - SPOTTERS_AMOUNT=${SPOTTERS_AMOUNT:-0}
      - SPOTTERS_TIME_WINDOW=3600
      - TRACE=${TRACE:-false}
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8777:8000"

networks:
  exorde-network:
    name: exorde-network
    driver: bridge
