version: '3.9'

services:
  upipe:
    networks:
      - exorde-network
    ports:
      - "7998:8000"
    labels:
      - "network.exorde.monitor=true"
      - "network.exorde.service=upipe"
    restart: always
    image: exordelabs/upipe:latest
    environment:
      - batch_target=http://bpipe:8000
    init: true
    deploy:
      replicas: ${UPIPE_SIZE:-1}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s

  bpipe:
    networks:
      - exorde-network
    ports:
      - "7999:8000"
    labels:
      - "network.exorde.monitor=true"
      - "network.exorde.service=bpipe"
    restart: always
    image: exordelabs/bpipe:latest
    environment:
      - transactioneer=http://transactioneer:8000
      - batch_size=20
    init: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 6G

  transactioneer:
    networks:
      - exorde-network
    labels:
      - "network.exorde.monitor=true"
      - "network.exorde.service=transactioneer"
    volumes:
      - ./config:/root/.config
    restart: always
    ports:
      - "7991:8000"
    image: exordelabs/transactioneer:latest
    environment:
      - main_address=${MAIN_ADDRESS}
    init: true
    working_dir: /app/
    command: python3.10 /app/transactioneer.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s

  orchestrator:
    networks:
      - exorde-network
    restart: always
    environment:
      - FILTER=network.exorde.monitor:true
      - ORCHESTRATE=${ORCHESTRATE:-0}
      - REFRESH_TIME=3600
    image: exordelabs/orchestrator:latest
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8777:8080"

networks:
  exorde-network:
    name: exorde-network
    driver: bridge
