global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090
- job_name: 'docker-services'
  static_configs:
    - targets:
      - scraper:8000
      - 172.17.0.1:9100
      - processor:7998
      - batch_processor:7999
      - transactioneer:7991
      - cadvisor:8080
      - youtube:8000
      - weibo:8000
      - rss:8000
      - hn:8000