version: '3'

services:
  prometheus:
    restart: always
    image: prom/prometheus:v2.48.0
    networks:
      - exorde-network
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    restart: always
    image: grafana/grafana:latest
    networks:
      - exorde-network
    user: "1000"
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
  cadvisor:
    restart: always
    image: gcr.io/cadvisor/cadvisor:latest
    networks:
      - exorde-network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '8080:8080'
    labels:
      io.prometheus.scrape: 'true'
      io.prometheus.port: '8080'

  jaeger:
    restart: always
    image: jaegertracing/all-in-one:latest
    networks:
      - exorde-network
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
      AGENT_MAX_PACKET_SIZE: 400459


networks:
  exorde-network:
    external: true
