version: '3.9'

services:
  upipe:
    networks:
      - exorde-network
    labels:
      - "network.exorde.monitor=true"
      - "network.exorde.service=upipe"
    restart: always
    build:
      context: ./upipe
    environment:
      - batch_target=http://bpipe:8000
    init: true
    working_dir: /app/
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s

  bpipe:
    networks:
      - exorde-network
    labels:
      - "network.exorde.monitor=true"
      - "network.exorde.service=bpipe"
    restart: always
    build:
      context: ./bpipe
    environment:
      - transactioneer=http://transactioneer:8000
      - batch_size=20
    init: true
    working_dir: /app/
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 6G

  transactioneer:
    networks:
      - exorde-network
    labels:
      - "network.exorde.monitor=true"
      - "network.exorde.service=transactioneer"
    volumes:
      - ./config:/root/.config
    restart: always
    ports:
      - "7991:8000"
    build:
      context: ./transactioneer
    environment:
      - main_address=${MAIN_ADDRESS}
    init: true
    working_dir: /app/
    command: python3.10 /app/transactioneer.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s

  container_scout:
    networks:
      - exorde-network
    restart: always
    environment:
      - FILTER=network.exorde.monitor:true
      - ORCHESTRATE=2
      - REFRESH_TIME=3600
    build:
      context: ./container_scout
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8777:8000"

networks:
  exorde-network:
    name: exorde-network
    driver: bridge
