version: '3.9'

services:
  transactioneer:
    volumes:
      - ./config:/root/.config
    restart: always
    ports:
      - "7991:7991"
    build:
      context: ./transactioneer
    environment:
      - main_address=0x2DBc451a2BAd2aDFfEF5d69C393A423D02D4f531
    init: true
    working_dir: /app/
    command: python3.10 /app/transactioneer.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7991/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s

  bpipe:
    restart: always
    ports:
      - "7999:7999"
    build:
      context: ./bpipe
    environment:
      - main_address=0x2DBc451a2BAd2aDFfEF5d69C393A423D02D4f531 # todo: remove
      - transactioneer=http://transactioneer:7991
      - batch_size=20
    init: true
    working_dir: /app/
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7999/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 6G
            #devices:
            #- driver: nvidia
            #  count: 1
            #  capabilities: [gpu]

  upipe_a:
    restart: always
    ports:
      - "7998:7998"
    build:
      context: ./upipe
    environment:
      - main_address=0x2DBc451a2BAd2aDFfEF5d69C393A423D02D4f531 # todo remove
      - batch_target=http://bpipe:7999
    init: true
    working_dir: /app/
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7998/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s

  upipe_b:
    restart: always
    ports:
      - "7988:7998"
    build:
      context: ./upipe
    environment:
      - main_address=0x2DBc451a2BAd2aDFfEF5d69C393A423D02D4f531 # todo remove
      - batch_target=http://bpipe:7999
    init: true
    working_dir: /app/
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7998/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s
