version: '3.9'

services:
  upipe:
    restart: always
    build:
      context: ./upipe
    environment:
      - batch_target=http://bpipe:7999
    init: true
    working_dir: /app/
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7998/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s
    deploy:
      replicas: 2

  bpipe:
    restart: always
    build:
      context: ./bpipe
    environment:
      - transactioneer=http://transactioneer:7991
      - batch_size=20
    init: true
    working_dir: /app/
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7999/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 6G
            #devices:
            #- driver: nvidia
            #  count: 1
            #  capabilities: [gpu]

  transactioneer:
    volumes:
      - ./config:/root/.config
    restart: always
    ports:
      - "7991:7991"
    build:
      context: ./transactioneer
    environment:
      - main_address=${MAIN_ADDRESS}
    init: true
    working_dir: /app/
    command: python3.10 /app/transactioneer.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7991/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 180s
